const MEGA_MAN_CONSTS = {
	QUEUE_INTERVAL: 55,
	MAX_QUEUE_LENGTH: 1,
	LARGE_PICKUP_DONATION_THRESHOLD: 100,
	MOVE_SPEED_FOREGROUND: 1,
	MOVE_SPEED_ENEMY: 2,
	MOVE_SPEED_BULLET: 4,
	MOVE_SPEED_TELEPORT: 4,
	JUMP_MEGA_MAN_INITIAL: -4,
	JUMP_MEGA_MAN_GRAVITY: 0.25,
	JUMP_PICKUP_INITIAL: -2,
	JUMP_PICKUP_GRAVITY: 0.25,
};

export default MEGA_MAN_CONSTS;