name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version-file: 'package.json'

      - uses: actions/checkout@v2
      - run: |
          npm ci
          npm run build
          npm run build:test
